import { afterEach, describe, expect, mock, test } from "bun:test";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
let selects: unknown[] = [];
mock.module("@clack/prompts", () => ({ intro: () => {}, cancel: () => {}, isCancel: (v: unknown) => typeof v === "symbol", log: { success: () => {}, info: () => {}, warn: () => {}, error: () => {} }, note: () => {}, outro: () => {}, select: async () => selects.shift(), multiselect: async () => selects.shift(), spinner: () => ({ start: () => {}, message: () => {}, stop: () => {} }) }));
import { runInteractive } from "../src/ui.js";
const dirs: string[] = [];
afterEach(() => { dirs.splice(0).forEach((d) => rmSync(d, { recursive: true, force: true })); selects = []; });
test("category navigation, review, destination, and confirmation install", async () => { const root = mkdtempSync(join(tmpdir(), "grimoire-ui-")); dirs.push(root); const catalog = join(root, "catalog"); mkdirSync(join(catalog, "alpha"), { recursive: true }); writeFileSync(join(catalog, "alpha", "SKILL.md"), "# alpha\n"); selects = ["category:Other", ["alpha"], ["alpha"], "confirm"]; expect(await runInteractive({ catalogDir: catalog, home: root, targetDirOverride: join(root, "target") })).toBe(0); });
test("cancellation never installs", async () => { const root = mkdtempSync(join(tmpdir(), "grimoire-ui-")); dirs.push(root); const catalog = join(root, "catalog"); mkdirSync(join(catalog, "alpha"), { recursive: true }); writeFileSync(join(catalog, "alpha", "SKILL.md"), "# alpha\n"); selects = [Symbol("cancel")]; expect(await runInteractive({ catalogDir: catalog, home: root, targetDirOverride: join(root, "target") })).toBe(1); });
